### ISSUE TITLE
请求支持深色模式

### ISSUE THREAD

**Issue by TheWhiteDog9487** [sy-records/MemorialDay#10]
我用WP Dark Mode让网站支持了深浅色切换，但是深色模式下灰色滤镜失效，想说能不能支持下这个功能

**Comment by sy-records** [comment]
深色模式下灰色应该怎么展示 🤔

**Comment by sy-records** [comment]
现在这个还可以啊？我在我的站点测试

![Image](https://github.com/user-attachments/assets/059470c6-1db0-41e5-8271-4cc15e2e7c4d)

**Comment by sy-records** [comment]
你的站点使用媒体查询 把这个改一下就好了

![Image](https://github.com/user-attachments/assets/fdaf0a48-bece-4558-9916-1760736e9c8b)

**Comment by TheWhiteDog9487** [comment]
这状态我觉得有点怪。
我开issue之前我测试的时候是浅色模式生效没问题深色模式没反应。
我刚去测试，结果变成了深色模式有用但是不完整（见下图），按钮切换到浅色模式，浅色模式没反应了。
不知道什么情况。

<img width="1920" alt="Image" src="https://github.com/user-attachments/assets/ee434d3b-3470-4047-9953-b66702c15706" />
<img width="1920" alt="Image" src="https://github.com/user-attachments/assets/c7de1761-6138-47f6-ad9e-c6459094b502" />

**Comment by sy-records** [comment]
```css
@media (prefers-color-scheme: dark) {
    html[data-wp-dark-mode-preset="0"] {
        filter: grayscale(1) !important
    }
}
```
